::: {.content-visible when-format="html"}

A thesis submitted for the degree of {{< meta degree >}} at the University of Ottawa, {{< meta faculty >}}, {{< meta department >}}.

:::

# Abstract {-}

The abstract should outline the main approach and findings of the thesis and must not be more than 500 words.

# Sommaire {-}

The abstract but in french this time.

# Declaration {-}

#### Reproducibility statement
```{r}
r_vers <- function(){
  paste0("v", version$major, ".", version$minor,", ", version$nickname)
}
```

This thesis was written using Quarto [@Quarto] and the R Statistical Software `r r_vers()` [@base], and the R packages listed in @tbl-pkgs. All materials (including the data sets and source files) required to reproduce this document can be found at the Github repository [`github.com/youraccount/thesis`](https://github.com/youraccount/thesis).

This work is licensed under a [Creative Commons  Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).

#### Author declaration

I hereby declare that this thesis contains no material which has been accepted for the award of any other degree or diploma at any university or equivalent institution and that, to the best of my knowledge and belief, this thesis contains no material previously published or written by another person, except where due reference is made in the text of the thesis.

The ideas, development and writing up of all the papers in the thesis were the principal responsibility of myself, the student, working under the supervision of {{< meta supervisor >}}. The inclusion of co-authors reflects the fact that the work came from active collaboration between researchers and acknowledges input into team-based research. This thesis was written in manuscript style and I have renumbered sections of submitted or published papers in order to generate a consistent presentation within the thesis.


# Co-authorship statement {.unnumbered} 

The following people and institutions contributed to the publications included in this thesis:

* Bob Hette (BH): University of Ottawa, Canada
* Igor Tex (IT): University of Textile, Softland
* Julien Martin (JGAM): University of Ottawa, Canada 


**My first manuscript**.

Integrated as Chapter 2 in this thesis. Under review at time of submission.

[Authors]{.underline}: 

* BH: Conceptualization, Investigation, Data curation, Formal analysis, Writing -Original Draft.
* IT: Writing - Review & Editing.
* JGAM: Conceptualization, Resources, Supervision, Writing - Review & Editing.

**My second manuscript**.

Integrated as Chapter 3 in this thesis. Under review at time of submission.

[Authors]{.underline}: 

* BH: Conceptualization, Investigation, Data curation, Formal analysis, Writing -Original Draft.
* IT: Writing - Review & Editing.
* JGAM: Conceptualization, Resources, Supervision, Writing - Review & Editing.



# Acknowledgements {.unnumbered}

I would like to thank my pet goldfish for ...

> If you have engaged the services of a professional editor, you must provide their name and a brief description of the service rendered. If the professional editor's current or former area of academic specialisation is similar your own, this too should be stated as it may suggest to examiners that the editor's advice to the student has extended beyond guidance on English expression to affect the substance and structure of the thesis.

> If you have used generative artificial intelligence (AI) technologies, you must include a written acknowledgment of the use and its extent. Your acknowledgement should at a minimum specify which technology was used, include explicit description on how the information was generated, and explain how the output was used in your work. Below is a suggested format:

> “I acknowledge the use of [insert AI system(s) and link] to [specific use of generative artificial intelligence]. The output from these was used to [explain use].”

> Free text section for you to record your acknowledgment and gratitude for the more general academic input and support such as financial support from grants and scholarships and the non-academic support you have received during the course of your enrolment. 

> You may also wish to acknowledge significant and substantial contribution made by others to the research, work and writing represented and/or reported in the thesis. These could include significant contributions to: the conception and design of the project; non-routine technical work; analysis and interpretation of research data; drafting significant parts of the work or critically revising it so as to contribute to the interpretation.


# Indigenous affirmation {.unnumbered}

> Ni manàdjiyànànig Màmìwininì Anishinàbeg, ogog kà nàgadawàbandadjig iyo akì eko weshkad.
> Ako nongom egawìkàd kì mìgiwewàdj.
> Ni manàdjiyànànig kakina Anishinàbeg ondaje kaye ogog kakina eniyagizidjig enigokamigàg
> Kanadàng eji ondàpinangig endàwàdjin Odàwàng.
> Ninisidawinawànànig kenawendamòdjig kije kikenindamàwin; weshkinìgidjig kaye
> kejeyàdizidjig.
> Nigijeweninmànànig ogog kà nìgànì sòngideyedjig; weshkad, nongom; kaye àyànikàdj.

> We pay respect to the Algonquin people, who are the traditional guardians of this land.
> We acknowledge their longstanding relationship with this territory, which remains unceded.
> We pay> respect to all Indigenous people in this region, from all nations across Canada, who call Ottawa home.
> We acknowledge the traditional knowledge keepers, both young and old.
> And we honour their courageous leaders: past, present, and future.

This Indigenous Affirmation was written the Office of Indigenous Affairs at the University of
Ottawa, in partnership with the Indigenous Education Council, Indigenous student groups, and
members of the local Indigenous community (https://www.uottawa.ca/about-
us/indigenous/indigenous-affirmation). This statement acknowledges that the University of
Ottawa, including the Kerr lab where I completed work for this thesis, was built on the
traditional territory of the Algonquin Nation. I collected all the data for this thesis within the
boundary of the City of Ottawa, which includes the traditional territory of the Algonquin Nation
and the Mohawk Nation (https://native-land.ca/). I acknowledge my own settler history, as well
as the colonial history of the University of Ottawa. I will continue to educate myself on Canada’s
colonial past and current Indigenous issues, and to leverage any power I have for
(re)conciliation.



<!--
The following line is required to generate toc, lof and lot, as well as change page numbering style. Do not remove
-->

{{< include _extensions/juliengamartin/bio-uo-thesis/end_frontmatter.tex >}}

